# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4503af8690c2a3abddd4e6a5a16731b88814cb3825623e63b1a0b394a01c8969543161fd8be3b6e033cd2b7552a1777b149fa440b4680ba8a76d57813d39a69d

test:
  secret_key_base: 70eed55a010152d298a6f031f50481c12b10174e2951e508be99841ffc50e215a3d7cabfe6d1f08885f22d611206c8a02802899b267358aa2347326a38761d41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
